[package]
name = "candle-d3d12-kernels"
version = "0.9.2"
edition = "2021"

description = "D3D12 compute shader kernels for Candle"
repository = "https://github.com/huggingface/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]
half = { version = "2.5.0", features = ["num-traits", "use-intrinsics", "rand_distr"] }
thiserror = "2"
tracing = "0.1"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58"
features = [
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
]
